### ISSUE TITLE
Not working in iOS 11? 

### ISSUE THREAD

**Issue by eshwartm** [truecaller/ios-sdk#11]
I pressed the button to call `TCTrueSDK.sharedManager().requestTrueProfile()` after all the setup with keys. It just opens a Safari page and says `Swipe down and tap OPEN to return to the App`. There is no OPEN button anywhere to return to the app.

What could be the problem? I have installed the TrueCaller app also.

**Comment by bi1zi1** [comment]
It could be the case that the Truecaller app was not properly registered for universal links by the operating system. Could you try and re-install the Truecaller app?

**Comment by eshwartm** [comment]
Reinstalled. This time the app opens, and I reach a "Continue as `username`" screen with a green button. When I press the button, it opens up the Safari browser with that same page as my original question -> `Swipe down and tap OPEN to return to the App`, with no OPEN button.

**Comment by eshwartm** [comment]
I'm sorry, it works, my bad. I had the app link wrong. I had put `applinks://` rather than just `applinks:`.

**Comment by bi1zi1** [comment]
Can you check your device (console) logs. 
Look for any service (usually swcd) trying to access apple-app-site-association and if it succeeds?
Check for both apps.

**Comment by RKhadsare** [comment]
Hi Team, Im facing this issue in iOS 12. Any update?

**Comment by prateek550** [comment]
Hi,
It works for me on iOS 12. But facing this issue on iOS 11 devices.
As it's working on iOS 12, I don't think the problem is with bundle id registration or configuration.
