### ISSUE TITLE
The signatureAlgorithm from the didReceiveTrueProfileResponse method is an empty string？

### ISSUE THREAD

**Issue by yangcaimu** [truecaller/ios-sdk#15]
In the didReceiveTrueProfileResponse delegate payload, signature, requestNonce are all valued, but signatureAlgorithm is an empty string.

**Comment by ankitgarg1mg** [comment]
I got same issue. Yet to found any solution

**Comment by singhalyogesh** [comment]
This issue had been fixed in the recent update we made to the SDK. Request all to please check that

**Comment by yangcaimu** [comment]
The recent SDK has fixed this issue. 🎉
