### ISSUE TITLE
How long does it take to generate app link?

### ISSUE THREAD

**Issue by Debhora1** [truecaller/ios-sdk#18]
I have created iOS app on truecaller developer profile. The app link is blank. How long does it take to generate. The app link field is blank and i cannot integrate truecaller sdk in iOS app without app link
<img width="1226" alt="Screenshot 2019-07-30 at 6 23 26 PM" src="https://user-images.githubusercontent.com/51984752/62130806-6acd0c80-b2f7-11e9-938c-791d6a41cb1c.png">

**Comment by kay14** [comment]
@Debhora1 Is your app link generated already? I have a similar situation at my end.

**Comment by jairusfdes** [comment]
I had the same issue. What i did was open my app in the dashboard https://developer.truecaller.com/dashboard/apps/{app id text}
Using the {app id text} part i created the app link as such

- applinks:{app id text}.truecallerdevs.com

on the dashboard the app link is still blank as above, but using the one i constructed it worked fine. @Debhora1 @kay14

**Comment by Debhora1** [comment]
@jairusfdes Yes used this method and it worked. Closing issue. Thanks.

**Comment by avanya** [comment]
Hi, I did the same but then also the delegate methods are not being executed. Can you please help me know what I might be doing wrong?
