### ISSUE TITLE
(TCTrueProfileResponse *) [url parseArchivedObjectWithKey:kTrueProfileResponseKey]; returns nil

### ISSUE THREAD

**Issue by prajakta27** [truecaller/ios-sdk#9]
Hi,

We integrated true caller lately and we have started getting a crash with the sdk. with little investigation we found that sometimes

(TCTrueProfileResponse *) [url parseArchivedObjectWithKey:kTrueProfileResponseKey];
in class TCTrueSDK.m returns nil which is causing the crash.

Please let us know how to resolve this issue.
or file this as an issue if its related to SDK.

**Comment by composers** [comment]
Hello,

Thank you for the investigation. We will soon take a look and get back to you. Do you have any specific scenario when this happens?

**Comment by prajakta27** [comment]
No. Its randomly crash.

**Comment by prajakta27** [comment]
Hie,

I'm still waiting for your response. This feature is important for our product, could you please check this issue and response back as soon as possible?

**Comment by composers** [comment]
Hello,

Please contact our TrueSDK support using this link:

https://developer.truecaller.com/contact

After that, we will prioritize this issue and take it further.

Thank you.
